services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-agent-api
    network_mode: "host"
    environment:
      OLLAMA_HOST: "http://127.0.0.1:11434"
      CHAT_OLLAMA_HOST: "http://127.0.0.1:11434"
      CHAT_OLLAMA_MODEL_ID: "llama3.1"
      CHAT_API_HOST: "0.0.0.0"
      CHAT_API_PORT: "8000"
    volumes:
      - .:/app
